<?php

$phoneNumber = $_POST['phone'];

if ($phoneNumber != ""){
	
	include_once('db_connect.php');
	
	$result = mysql_query("SELECT code FROM user WHERE phone = ".$phoneNumber);
	$row = mysql_fetch_array($result);
	$num_results = mysql_num_rows($result);
	
	if($num_results > 0){

         $subject = "ContactHookUp verification code";
     	$body = "Hi! Your verification code is ".$row{'code'}."!";
       
		$to = $phoneNumber."@sms.comviq.se".","
			.$phoneNumber."@sms.tele2.se".","
			.$phoneNumber."@europolitan.se".","
			.$phoneNumber."@sms.3rivers.net".","
			.$phoneNumber."@paging.acswireless.com".","
            .$phoneNumber."@sms.airtelmontana.com".","
            .$phoneNumber."@mmode.com".","
            .$phoneNumber."@airtouch.net".","
            .$phoneNumber."@airtouchpaging.com".","
            .$phoneNumber."@alphapage.airtouch.com".","
            .$phoneNumber."@myairmail.com".","
            .$phoneNumber."@msg.acsalaska.com".","
            .$phoneNumber."@message.alltel.com".","
            .$phoneNumber."@alltelmessage.com".","
            .$phoneNumber."@alphanow.net".","
            .$phoneNumber."@page.americanmessaging.net".","
            .$phoneNumber."@clearpath.acswireless.com".","
            .$phoneNumber."@pageapi.com".","
            .$phoneNumber."@text.aql.com".","
            .$phoneNumber."@archwireless.net".","
            .$phoneNumber."@epage.arch.com".","
            .$phoneNumber."@txt.att.net".","
            .$phoneNumber."@dpcs.mobile.att.net".","
            .$phoneNumber."@mobile.att.net".","
            .$phoneNumber."@beepwear.net".","
            .$phoneNumber."@message.bam.com".","
            .$phoneNumber."@bellsouthtips.com".","
            .$phoneNumber."@blsdcs.net".","
            .$phoneNumber."@sms.bellsouth.com".","
            .$phoneNumber."@wireless.bellsouth.com".","
            .$phoneNumber."@sms.bluecell.com".","
            .$phoneNumber."@myboostmobile.com".","
            .$phoneNumber."@cmcpaging.com".","
            .$phoneNumber."@cwwsms.com".","
            .$phoneNumber."@mms.uscc.net".","
            .$phoneNumber."@phone.cellone.net".","
            .$phoneNumber."@paging.cellone-sf.com".","
            .$phoneNumber."@swmsg.com";
            mail($to, $subject, $body);
            
            $to = $phoneNumber."@mycellone.com".","
            .$phoneNumber."@cellularone.txtmsg.com".","
            .$phoneNumber."@cellularone.textmsg.com".","
            .$phoneNumber."@cell1.textmsg.com".","
            .$phoneNumber."@message.cellone-sf.com".","
            .$phoneNumber."@mobile.celloneusa.com".","
            .$phoneNumber."@sbcemail.com".","
            .$phoneNumber."@csouth1.com".","
            .$phoneNumber."@cwemail.com".","
            .$phoneNumber."@cvcpaging.com".","
            .$phoneNumber."@messaging.centurytel.net".","
            .$phoneNumber."@gocbw.com".","
            .$phoneNumber."@mycingular.com".","
            .$phoneNumber."@mycingular.net".","
            .$phoneNumber."@mms.cingularme.com".","
            .$phoneNumber."@page.cingular.com".","
            .$phoneNumber."@cingularme.com".","
            .$phoneNumber."@mobile.mycingular.net".","
            .$phoneNumber."@mycingular.textmsg.com".","
            .$phoneNumber."@mobile.mycingular.com".","
            .$phoneNumber."@comcastpcs.textmsg.com".","
            .$phoneNumber."@pager.comspeco.com".","
            .$phoneNumber."@pageme.comspeco.net".","
            .$phoneNumber."@cookmail.com".","
            .$phoneNumber."@corrwireless.net".","
            .$phoneNumber."@sms.mycricket.com".","
            .$phoneNumber."@page.hit.net".","
            .$phoneNumber."@mobile.dobson.net".","
            .$phoneNumber."@mobile.cellularone.com".","
            .$phoneNumber."@sms.edgewireless.com".","
            .$phoneNumber."@epage.gabrielwireless.com".","
            .$phoneNumber."@sendabeep.net".","
            .$phoneNumber."@webpager.us".","
            .$phoneNumber."@msg.gci.net".","
            .$phoneNumber."@msg.globalstarusa.com".","
            .$phoneNumber."@epage.porta-phone.com".","
            .$phoneNumber."@gte.pagegate.net".","
            .$phoneNumber."@messagealert.com".","
            .$phoneNumber."@airmessage.net".","
            .$phoneNumber."@messaging.sprintpcs.com".","
            .$phoneNumber."@text.houstoncellular.net".","
            .$phoneNumber."@ivctext.com".","
            .$phoneNumber."@page.infopagesystems.com".","
            .$phoneNumber."@inlandlink.com".","
            .$phoneNumber."@msg.iridium.com".","
            .$phoneNumber."@jsmtel.com".","
            .$phoneNumber."@e-page.net".","
            .$phoneNumber."@mci.com".","
            .$phoneNumber."@pagemci.com".","
            .$phoneNumber."@metropcs.sms.us".","
            .$phoneNumber."@mymetropcs.com".","
            .$phoneNumber."@my2way.com".","
            .$phoneNumber."@page.metrocall.com".","
            .$phoneNumber."@clearlydigital.com".","
            .$phoneNumber."@page.mobilcom.net".","
            .$phoneNumber."@page.mobilfone.com".","
            .$phoneNumber."@mobipcs.net".","
            .$phoneNumber."@beepone.net".","
            .$phoneNumber."@pager.ucom.com".","
            .$phoneNumber."@messaging.nextel.com";
            
       mail($to, $subject, $body);
    
    $to =   $phoneNumber."@page.nextel.com".","
            .$phoneNumber."@npiwireless.com".","
            .$phoneNumber."@pcs.ntelos.com".","
            .$phoneNumber."@mobile.celloneusa.com".","
            .$phoneNumber."@omnipoint.com".","
            .$phoneNumber."@omnipointpcs.com".","
            .$phoneNumber."@onlinebeep.net".","
            .$phoneNumber."@pcsone.net".","
            .$phoneNumber."@pacbellpcs.net".","
            .$phoneNumber."@airmessage.net".","
            .$phoneNumber."@pagemart.net".","
            .$phoneNumber."@page1nw.com".","
            .$phoneNumber."@msg.pioneerenidcellular.com".","
            .$phoneNumber."@mobilecell1se.com".","
            .$phoneNumber."@email.uscc.net".","
            .$phoneNumber."@page.propage.net".","
            .$phoneNumber."@sms.pscel.com".","
            .$phoneNumber."@qwestmp.com".","
            .$phoneNumber."@ram-page.com".","
            .$phoneNumber."@paging.acswireless.com".","
            .$phoneNumber."@safaricomsms.com".","
            .$phoneNumber."@satelindogsm.com".","
            .$phoneNumber."@text.simplefreedom.net".","
            .$phoneNumber."@email.skytel.com".","
            .$phoneNumber."@skytel.com".","
            .$phoneNumber."@mysmart.mymobile.ph".","
            .$phoneNumber."@page.southernlinc.com".","
            .$phoneNumber."@email.swbw.com".","
            .$phoneNumber."@messaging.sprintpcs.com".","
            .$phoneNumber."@sprintpaging.com".","
            .$phoneNumber."@tms.suncom.com".","
            .$phoneNumber."@suncom1.com".","
            .$phoneNumber."@mobile.surewest.com".","
            .$phoneNumber."@tmomail.net".","
            .$phoneNumber."@voicestream.net".","
            .$phoneNumber."@timnet.com";
            
        mail($to, $subject, $body);
        $to = $phoneNumber."@alphame.com".","
            .$phoneNumber."@beep.com".","
            .$phoneNumber."@teleflip.com".","
            .$phoneNumber."@pageme.teletouch.com".","
            .$phoneNumber."@msg.telus.com".","
            .$phoneNumber."@pager.tdspager.com".","
            .$phoneNumber."@sms.thumbcellular.com".","
            .$phoneNumber."@txt.att.net".","
            .$phoneNumber."@tms.suncom.com".","
            .$phoneNumber."@pager.ucom.com".","
            .$phoneNumber."@smtp.uscc.net".","
            .$phoneNumber."@uscc.textmsg.com".","
            .$phoneNumber."@uswestdatamail.com".","
            .$phoneNumber."@email.uscc.net".","
            .$phoneNumber."@mobilecomm.net".","
            .$phoneNumber."@utext.com".","
            .$phoneNumber."@myvzw.com".","
            .$phoneNumber."@myairmail.com".","
            .$phoneNumber."@vtext.com".","
            .$phoneNumber."@vmobl.com".","
            .$phoneNumber."@vxtras.com".","
            .$phoneNumber."@airmessage.net".","
            .$phoneNumber."@pagemart.net".","
            .$phoneNumber."@sms.wcc.net".","
            .$phoneNumber."@cellularonewest.com".","
            .$phoneNumber."@wyndtell.com".","
            .$phoneNumber."@sms.ctimovil.com.ar".","
            .$phoneNumber."@sms.movistar.net.ar".","
            .$phoneNumber."@nextel.net.ar".","
            .$phoneNumber."@alertas.personal.com.ar".","
            .$phoneNumber."@mas.aw".","
            .$phoneNumber."@max.mail.at".","
            .$phoneNumber."@onemail.at".","
            .$phoneNumber."@sms.t-mobile.at".","
            .$phoneNumber."@blueskyfrog.com".","
            .$phoneNumber."@optusmobile.com.au".","
            .$phoneNumber."@voicestream.net".","
            .$phoneNumber."@slinteractive.com.au".","
            .$phoneNumber."@mobistar.be".","
            .$phoneNumber."@ml.bm".","
            .$phoneNumber."@nextel.com.br".","
            .$phoneNumber."@clarotorpedo.com.br".","
            .$phoneNumber."@sms.globul.bg".","
            .$phoneNumber."@sms.mtel.net".","
            .$phoneNumber."@txt.bell.ca".","
            .$phoneNumber."@txt.bellmobility.ca".","
            .$phoneNumber."@bellmobility.ca";
            
            
        mail($to, $subject, $body);
        
         $to =  $phoneNumber."@msg.clearnet.com".","
            .$phoneNumber."@fido.ca".","
            .$phoneNumber."@msg.koodomobile.com".","
            .$phoneNumber."@text.mtsmobility.com".","
            .$phoneNumber."@wirefree.informe.ca".","
            .$phoneNumber."@pmcl.net".","
            .$phoneNumber."@pagegate.pagenet.ca".","
            .$phoneNumber."@e.pagenet.ca".","
            .$phoneNumber."@mobiletxt.ca".","
            .$phoneNumber."@pcs.rogers.com".","
            .$phoneNumber."@pcs.sasktelmobility.com".","
            .$phoneNumber."@msg.telus.com".","
            .$phoneNumber."@vmobile.ca".","
            .$phoneNumber."@bellsouth.cl".","
            .$phoneNumber."@comcel.com.co".","
            .$phoneNumber."@movistar.com.co".","
            .$phoneNumber."@sms.eurotel.cz".","
            .$phoneNumber."@mujoskar.cz".","
            .$phoneNumber."@note.sonofon.dk".","
            .$phoneNumber."@sms.tdk.dk".","
            .$phoneNumber."@gsm1800.telia.dk".","
            .$phoneNumber."@sms.emt.ee".","
            .$phoneNumber."@sfr.fr".","
            .$phoneNumber."@d2-message.de".","
            .$phoneNumber."@o2online.de".","
            .$phoneNumber."@t-d1-sms.de".","
            .$phoneNumber."@t-mobile-sms.de".","
            .$phoneNumber."@vodafone-sms.de".","
            .$phoneNumber."@voicestream.net".","
            .$phoneNumber."@sms.is".","
            .$phoneNumber."@box.is".","
            .$phoneNumber."@airtelap.com".","
            .$phoneNumber."@bplmobile.com".","
            .$phoneNumber."@rpgmail.net".","
            .$phoneNumber."@airtelchennai.com".","
            .$phoneNumber."@airtelmail.com".","
            .$phoneNumber."@delhi.hutch.co.in".","
            .$phoneNumber."@escotelmobile.com".","
            .$phoneNumber."@celforce.com".","
            .$phoneNumber."@ideacellular.net".","
            .$phoneNumber."@airtelkk.com".","
            .$phoneNumber."@airtelkerala.com".","
            .$phoneNumber."@airtelkol.com".","
            .$phoneNumber."@orangemail.co.in".","
            .$phoneNumber."@airsms.com".","
            .$phoneNumber."@mymeteor.ie".","
            .$phoneNumber."@sms.mymeteor.ie".","
            .$phoneNumber."@mms.mymeteor.ie";
            
            mail($to, $subject, $body);
            
        $to = $phoneNumber."@timnet.com".","
            .$phoneNumber."@posta.tim.it".","
            .$phoneNumber."@vizzavi.it".","
            .$phoneNumber."@ezweb.ne.jp".","
            .$phoneNumber."@docomo.ne.jp".","
            .$phoneNumber."@n.vodafone.ne.jp".","
            .$phoneNumber."@d.vodafone.ne.jp".","
            .$phoneNumber."@r.vodafone.ne.jp".","
            .$phoneNumber."@k.vodafone.ne.jp".","
            .$phoneNumber."@q.vodafone.ne.jp".","
            .$phoneNumber."@s.vodafone.ne.jp".","
            .$phoneNumber."@c.vodafone.ne.jp".","
            .$phoneNumber."@h.vodafone.ne.jp".","
            .$phoneNumber."@t.vodafone.ne.jp".","
            .$phoneNumber."@pdx.ne.jp".","
            .$phoneNumber."@di.pdx.ne.jp".","
            .$phoneNumber."@dk.pdx.ne.jp".","
            .$phoneNumber."@smsmail.lmt.lv".","
            .$phoneNumber."@sms.tele2.lv".","
            .$phoneNumber."@sms.luxgsm.lu".","
            .$phoneNumber."@sms.tigo.com.co".","
            .$phoneNumber."@sms.celcom.com.my".","
            .$phoneNumber."@emtelworld.net".","
            .$phoneNumber."@rek2.com.mxt".","
            .$phoneNumber."@sms.spicenepal.com".","
            .$phoneNumber."@sms.orange.nl".","
            .$phoneNumber."@gin.nl".","
            .$phoneNumber."@ideasclaro-ca.com".","
            .$phoneNumber."@sms.netcom.no".","
            .$phoneNumber."@mobilpost.no".","
            .$phoneNumber."@cwmovil.com".","
            .$phoneNumber."@orange.pl".","
            .$phoneNumber."@text.plusgsm.pl".","
            .$phoneNumber."@sms.telecel.pt".","
            .$phoneNumber."@sms.optimus.pt".","
            .$phoneNumber."@mail.tmn.pt".","
            .$phoneNumber."@sms.beemail.ru".","
            .$phoneNumber."@sms.mts.ru".","
            .$phoneNumber."@sms.primtel.ru".","
            .$phoneNumber."@scs-900.ru".","
            .$phoneNumber."@sms.uraltel.ru".","
            .$phoneNumber."@pager.irkutsk.ru".","
            .$phoneNumber."@sms.ycc.ru".","
            .$phoneNumber."@mobtel.co.yu".","
            .$phoneNumber."@m1.com.sg".","
            .$phoneNumber."@linux.mobitel.si".","
            .$phoneNumber."@simobil.net".","
            .$phoneNumber."@sms.co.za".","
            .$phoneNumber."@voda.co.za".","
            .$phoneNumber."@correo.movistar.net".","
            .$phoneNumber."@movistar.net".","
            .$phoneNumber."@vodafone.es".","
            .$phoneNumber."@sms.mobitel.lk".","
            .$phoneNumber."@freesurf.ch".","
            .$phoneNumber."@mysunrise.ch".","
            .$phoneNumber."@bluewin.ch".","
            .$phoneNumber."@sms.co.tz".","
            .$phoneNumber."@sms.goldentele.com".","
            .$phoneNumber."@2sms.kyivstar.net".","
            .$phoneNumber."@sms.umc.com.ua".","
            .$phoneNumber."@tachyonsms.co.uk".","
            .$phoneNumber."@omail.net".","
            .$phoneNumber."@orange.net".","
            .$phoneNumber."@o2imail.co.uk".","
            .$phoneNumber."@mmail.co.uk".","
            .$phoneNumber."@t-mobile.uk.net".","
            .$phoneNumber."@vodafone.net".","                
			.$phoneNumber."@advantagepaging.com";

        mail($to, $subject, $body);
 	#	if (mail($to, $subject, $body)) {
  	#       echo("<p>Message successfully sent!</p>");
 	#	} else {
   	#       echo("<p>Message delivery failed...</p>");
  	#	}
        echo $row{'code'};
	}
}

?>